<?php
// Set page title.
$this->headTitle($this->translate('Oasisbr'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
  $this->searchClassId = 'Solr';
}

$this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
  <div class="search-img">
    <a href="<?= $this->url('home') ?>"> <img src="<?= $this->imageLink('oasisbr.png'); ?>" alt="Logo do OasisBR" /></a>
  </div>
  <?php $this->slot('search-home-hero')->start() ?>
  <?= $this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true]) ?>
  <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?= $this->slot('search-home-hero')->end() ?>
</div>
<!-- importa a seção de informações abaixo da busca na página inicial -->
<?= $this->render('content-home.phtml') ?>