<?php
$source = $this->transEsc("Source");
$titleName = $source;
?>
<?php $this->headTitle($titleName); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->nocontainerclass = true; ?>
<?php $this->headLink()->appendStylesheet('loader.css'); ?>
<?php $this->headScript()->appendFile("load-network.js"); ?>

<div class="logo-img-center">
  <a href="<?= $this->url('home') ?>"><img src="<?= $this->imageLink('oasisbr.png'); ?>" alt="Logo do OasisBR" /></a>
</div>

<div class="page-title-bar">
  <div class="container">
    <h1><?= $this->transEsc("Data Sources") ?></h1>
    <h4><?= $this->transEsc("Data Sources Subtitle") ?> <h4>
  </div>
</div>

<div class="container">
  <table class="table table-striped" id="dataSource">

  </table>
</div>