<?php $this->headTitle($this->translate('Data Sources')); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->nocontainerclass = true; ?>
<?php $this->headLink()->appendStylesheet('loader.css'); ?>
<?php $this->headScript()->appendFile("lib/list.min.js"); ?>
<?php $this->headScript()->appendFile("networks.js"); ?>

<div class="logo-img-center">
  <a href="<?= $this->url('home') ?>"><img src="<?= $this->imageLink('oasisbr.png'); ?>" alt="Logo do OasisBR" /></a>
</div>

<div class="page-title-bar">
  <div class="container">
    <h1><?= $this->transEsc("Data Sources") ?></h1>
    <h4><?= $this->transEsc("Data Sources Subtitle") ?><h4>
  </div>
</div>

<div class="container" id="networks-page" class="networks-page">
  <div class="sidebar left hidden-print" id="search-sidebar">
    <div class="facet-group" id="side-panel-format">
      <button class="title" aria-expanded="true" data-toggle="collapse">
        <?= $this->transEsc("Source type") ?> </button>
      <div id="side-collapse-format" class="collapse in" aria-expanded="true">
        <a id="list-all" class="facet js-facet-item facetAND">
          <span class="text">
            <span class="facet-value"><?= $this->transEsc("All sources") ?></span>
          </span>
          <span class="badge badge-total"> </span>
        </a>
      </div>
    </div>
    <div class="facet-group" id="side-panel-institution">
      <button class="title" aria-expanded="true" data-toggle="collapse">
        <?= $this->transEsc("Institution") ?>
      </button>
      <div id="side-collapse-institution" class="collapse in" aria-expanded="true">
        <a id="list-all" class="facet js-facet-item facetAND">
          <span class="text">

            <span class="facet-value"><?= $this->transEsc("All sources") ?></span>
          </span>
          <span class="badge badge-total"> </span>
        </a>
      </div>
    </div>

    <div class="facet-group" id="side-panel-region">
      <button class="title" aria-expanded="true" data-toggle="collapse">
        <?= $this->transEsc("Region") ?> </button>
      <div id="side-collapse-region" class="collapse in" aria-expanded="true">
        <a id="list-all" class="facet js-facet-item facetAND">
          <span class="text">

            <span class="facet-value"><?= $this->transEsc("All sources") ?></span>
          </span>
          <span class="badge badge-total"> </span>
        </a>
      </div>
    </div>

    <div class="facet-group" id="side-panel-uf">
      <button class="title" aria-expanded="true" data-toggle="collapse">
        <?= $this->transEsc("State") ?> </button>
      <div id="side-collapse-uf" class="collapse in" aria-expanded="true">
        <a id="list-all" class="facet js-facet-item facetAND">
          <span class="text">

            <span class="facet-value"><?= $this->transEsc("All sources") ?></span>
          </span>
          <span class="badge badge-total"> </span>
        </a>
      </div>
    </div>
    <button class="btn btn-secondary btn-block"><?= $this->transEsc("Clear filters") ?> </button>
  </div>

  <div class="mainbody right">
    <div class="top-facets">
      <!--Toggle for mobile collapse -->
      <a class="top-title js-toggle visible-xs" data-toggle="collapse" data-target="#top_topic_facet"><i class="fa fa-caret-right"></i> Sugestões de Tópicos dentro de sua ...</a>
      <!--Regular title for non-mobile -->
      <div class="collapse" id="top_topic_facet">
      </div>
    </div>
    <div id="result" class="search-header hidden-print">
      <div class="search-stats networks-total-label">
        <span class="networks-label">

        </span>
        <button class="btn btn-primary btn-export-csv ">
          <?= $this->transEsc("Export to") ?> CSV
        </button>
      </div>
    </div>

    <div id="networks">
      <div class="flex flex-space-between">
        <input class="search form-control" placeholder=<?= $this->transEsc("Search") ?>>
        <div class="networks-sort flex">
          <label for="sort-select"><?= $this->transEsc("Sort") ?></label>
          <select id="sort-select" class="form-control">
            <option value="asc"><?= $this->transEsc("Ascending") ?></option>
            <option value="desc"><?= $this->transEsc("Descending") ?></option>
          </select>
        </div>
      </div>
      <div class="loader"></div>

      <ol class="list" style="counter-reset: item 0">
      </ol>

      <ul class="pagination"></ul>
    </div>
  </div>


</div>