<footer class="hidden-print">
  <div class="container-fluid social-media">
    <div class="flex-row-center gap-2">
      <a href="https://www.youtube.com/user/IBICTbr/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('youtube.png'); ?>" alt="Youtube Logo" />
      </a>
      <a href="https://www.facebook.com/IBICTbr/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('facebook.png'); ?>" alt="Facebook Logo" />
      </a>
      <a href="https://twitter.com/ibictbr" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('twitter.png'); ?>" alt="Twitter Logo" />
      </a>
      <a href="https://www.linkedin.com/company/ibict---instituto-brasileiro-de-informa-o-em-ci-ncia-e-tecnologia/mycompany/" target="_blank">
        <img class="img-responsive" src="<?= $this->imageLink('linkedin.svg'); ?>" alt="Linkedin Logo" />
      </a>
    </div>
  </div>
  <div class="container-fuid footer">
    <div class="row flex-row-center">
      <div class="col-md-7 col-xs-12">
        <nav class="nav-footer">
          <ul>
            <li>
              <a href="#"><?= $this->transEsc("Home") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('about-home') ?>"><?= $this->transEsc("About") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('datasources-home') ?>"><?= $this->transEsc("Data Sources") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('indicators-home') ?>"><?= $this->transEsc("Indicators") ?></a>
            </li>
            <?php if ($this->feedback()->tabEnabled()) : ?>
              <li>
                <a id="feedbackLink" data-lightbox href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("Contact") ?></a>
              </li>
            <?php endif; ?>
          </ul>
        </nav>
      </div>
      <div class="col-md-5 col-xs-12 flex-row-center">
        <a class="icon-gov-links" href="https://www.gov.br/ibict" target="_blank" rel="noopener noreferrer"> <img class="img-responsive image-footer" src="<?= $this->imageLink('logo.svg'); ?>" alt="logo de assinatura do ibict" /></a>
        <a class="icon-gov-links" href="https://www.gov.br/ibict" target="_blank" rel="noopener noreferrer"> <img class="img-responsive image-footer small-image" src="<?= $this->imageLink('logo.svg'); ?>" alt="logo de assinatura do ibict" /></a>
      </div>
    </div>
    <div class="flex-row-center">
      <p class="text-center">
        Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict) <br />
        SAUS Quadra 5 - Lote 6 Bloco H - Asa sul - CEP: 70.070-912 - Brasília - DF
      </p>
    </div>
  </div>
  <script async src="https://barra.brasil.gov.br/barra_2.0.js"></script>
</footer>