<footer class="d-print-none">
  <div class="container-fluid social-media">
    <div class="flex-row-center gap-2">
      <a href="https://www.youtube.com/user/IBICTbr/" target="_blank" rel="noopener noreferrer">
        <img class="img-fluid" src="<?= $this->imageLink('youtube.png'); ?>" alt="Youtube" />
        <span class="visually-hidden"><?= $this->transEsc('Abre em nova aba') ?></span>
      </a>
      <a href="https://www.facebook.com/IBICTbr/" target="_blank" rel="noopener noreferrer">
        <img class="img-fluid" src="<?= $this->imageLink('facebook.png'); ?>" alt="Facebook" />
        <span class="visually-hidden"><?= $this->transEsc('Abre em nova aba') ?></span>
      </a>
      <a href="https://twitter.com/ibictbr" target="_blank" rel="noopener noreferrer">
        <img class="img-fluid" src="<?= $this->imageLink('twitter.png'); ?>" alt="Twitter" />
        <span class="visually-hidden"><?= $this->transEsc('Abre em nova aba') ?></span>
      </a>
      <a href="https://www.linkedin.com/company/ibict---instituto-brasileiro-de-informa-o-em-ci-ncia-e-tecnologia/mycompany/" target="_blank" rel="noopener noreferrer">
        <img class="img-fluid" src="<?= $this->imageLink('linkedin.svg'); ?>" alt="Linkedin" />
        <span class="visually-hidden"><?= $this->transEsc('Abre em nova aba') ?></span>
      </a>
    </div>
  </div>
  <div class="container-fluid footer">
    <div class="row flex-row-center">
      <div class="col-md-7 col-12">
        <nav class="nav-footer" aria-label="<?= $this->transEsc('Footer navigation') ?>">
          <ul>
            <li>
              <a href="<?= $this->url('home') ?>"><?= $this->transEsc("Home") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('about-home') ?>"><?= $this->transEsc("About") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('datasources-home') ?>"><?= $this->transEsc("Data Sources") ?></a>
            </li>
            <li>
              <a href="<?= $this->url('indicators-home') ?>"><?= $this->transEsc("Indicators") ?></a>
            </li>
            <?php if ($this->feedback()->tabEnabled()) : ?>
              <li>
                <a id="footerFeedbackLink" data-lightbox href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("Contact") ?></a>
              </li>
            <?php endif; ?>
          </ul>
        </nav>
      </div>
      <div class="col-md-5 col-12 flex-row-center">
        <a class="icon-gov-links" href="https://www.gov.br/ibict" target="_blank" rel="noopener noreferrer"> <img class="img-fluid image-footer" src="<?= $this->imageLink('logo.svg'); ?>" alt="logo de assinatura do ibict" /></a>
        <a class="icon-gov-links" href="https://www.gov.br/ibict" target="_blank" rel="noopener noreferrer" aria-hidden="true" tabindex="-1"> <img class="img-fluid image-footer small-image" src="<?= $this->imageLink('logo.svg'); ?>" alt="" /></a>
      </div>
    </div>
    <div class="flex-row-center">
      <address class="text-center">
        Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict) <br />
        SAUS Quadra 5 - Lote 6 Bloco H - Asa sul - CEP: 70.070-912 - Brasília - DF
      </address>
    </div>
  </div>
  <script async src="https://barra.brasil.gov.br/barra_2.0.js"></script>
</footer>