<?php $this->headTitle($this->translate('About')); ?>
<?php $this->layout()->searchbox = false; ?>

<!-- <div class="logo-img-center">
  <a href="<?= $this->url('home') ?>"><img class="img-responsive" src="<?= $this->imageLink('oasisbr.png'); ?>" alt="" /></a>
</div> -->
<div class="about">

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <h1> <?= $this->transEsc('about title'); ?> </h1>
        <p>
          <?= $this->transEsc('about p1'); ?>
        </p>
        <p>
          <?= $this->transEsc('about p2'); ?>
        </p>
        <p>
          <?= $this->transEsc('about p3'); ?>
          <a target="_blank" href="https://www.rcaap.pt" rel="noopener noreferrer" aria-label="<?= $this->transEsc('about link rcaap aria label'); ?>">
            <?= $this->transEsc('about link rcaap'); ?>
          </a>
        </p>
      </div>
    </div>
  </div>

  <div class="row objectives">
    <div class="col-md-12">
      <div class="card">
        <h2>
          <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#objetivos" aria-expanded="false" aria-controls="objetivos">
            <?= $this->transEsc('Goals'); ?>
          </button>
        </h2>
        <div class="collapse" id="objetivos">
          <ul>
            <li>
              <?= $this->transEsc('goal 1'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 2'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 3'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 4'); ?></li>
            <li>
              <?= $this->transEsc('goal 5'); ?></li>
            <li>
              <?= $this->transEsc('goal 6'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 7'); ?>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 network-flow" id="network-flow">
      <div class="card">
        <h2>
          <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#fluxo" aria-expanded="false" aria-controls="fluxo">
            <?= $this->transEsc('Oasisbr information flow'); ?>
          </button>
        </h2>
        <div class="collapse" id="fluxo">
          <p> <?= $this->transEsc('flow p1'); ?></p>
          <p>
            <?= $this->transEsc('flow p2'); ?>
            <!-- <a target="_blank" href="https://www.rcaap.pt" rel="noopener noreferrer" aria-label="<?= $this->transEsc('flow link rcaap aria label'); ?>">
              <?= $this->transEsc('about link rcaap'); ?>
            </a> -->
            <?= $this->transEsc('flow p3'); ?>
            <a target="_blank" href="https://www.lareferencia.info/pt"> <?= $this->transEsc('La Referencia'); ?></a>
            <?= $this->transEsc('flow p4'); ?>
            <a target="_blank" href="https://www.openaire.eu/">OpenAIRE</a>
            .
          </p>
          <p> <?= $this->transEsc('flow p5'); ?></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-12">
      <div class="card">

        <h2>
          <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#collecting" aria-expanded="false" aria-controls="collecting">
            <?= $this->transEsc('Criteria for collecting information sources'); ?>
          </button>
        </h2>

        <div class="collapse" id="collecting">
          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#monographs" aria-expanded="false" aria-controls="monographs">
              <?= $this->transEsc('Digital libraries of monographs'); ?>
            </button>
          </h3>
          <div class="collapse" id="monographs">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p3'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <a href="https://guidelines.openaire.eu/en/latest/literature/field_publicationtype.html" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm p13'); ?></a>;
              </li>
            </ul>
          </div>

          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#theses" aria-expanded="false" aria-controls="theses">
              <?= $this->transEsc('Digital libraries of electronic theses and dissertations'); ?>
            </button>
          </h3>
          <div class="collapse" id="theses">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('dtd p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <?= $this->transEsc('dtd p1'); ?>
                <a href="https://bdtd.ibict.br" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('BDTD'); ?>
                </a>
              </li>
            </ul>
          </div>

          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#events" aria-expanded="false" aria-controls="events">
              <?= $this->transEsc('Scientific conferences (Events)'); ?>
            </button>
          </h3>
          <div class="collapse" id="events">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p1'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p3'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p4'); ?>
              </li>
            </ul>
          </div>


          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#portals" aria-expanded="false" aria-controls="portals">
              <?= $this->transEsc('Aggregator portals'); ?>
            </button>
          </h3>
          <div class="collapse" id="portals">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('ap p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>,
                <a href="https://datacite.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('DataCite'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('ap p1'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <a href="https://guidelines.openaire.eu/en/latest/literature/field_publicationtype.html" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm p13'); ?></a>;
              </li>
            </ul>
          </div>


          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#book" aria-expanded="false" aria-controls="book">
              <?= $this->transEsc('Book portals'); ?>
            </button>
          </h3>
          <div class="collapse" id="book">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('ap p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  Dublin Core
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <a href="https://guidelines.openaire.eu/en/latest/literature/field_publicationtype.html" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm p13'); ?></a>;
              </li>
            </ul>
          </div>

          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#repositories" aria-expanded="false" aria-controls="repositories">
              <?= $this->transEsc('Research data repositories'); ?>
            </button>
          </h3>
          <div class="collapse" id="repositories">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('rr p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('rr p1'); ?>
                <a href="https://datacite.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('DataCite'); ?>
                </a>
                <?= $this->transEsc('rr p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('rr p3'); ?>
              </li>
              <li>
                <?= $this->transEsc('rr p4'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <?= $this->transEsc('rr p5'); ?>
              </li>
            </ul>
          </div>


          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#literature" aria-expanded="false" aria-controls="literature">
              <?= $this->transEsc('Literature repositories'); ?>
            </button>
          </h3>
          <div class="collapse" id="literature">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('lr p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <a href="https://guidelines.openaire.eu/en/latest/literature/field_publicationtype.html" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm p13'); ?></a>;
              </li>
            </ul>
          </div>

          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#journals" aria-expanded="false" aria-controls="journals">
              <?= $this->transEsc('Scientific journals'); ?>
            </button>
          </h3>
          <div class="collapse" id="journals">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('sc p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  Dublin Core
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('sj p1'); ?>
              </li>
              <li>
                <?= $this->transEsc('sj p2'); ?>
                <a href="https://diadorim.ibict.br" target="_blank" rel="noopener noreferrer">
                  Diadorim
                </a>
                <?= $this->transEsc('and/or'); ?>
                <a href="https://miguilim.ibict.br/" target="_blank" rel="noopener noreferrer">
                  Miguilim
                </a>
                ,
                <?= $this->transEsc('declaring that the journal is open access'); ?>
                .
              </li>
              <li>
                <?= $this->transEsc('sj p3'); ?>
                <a href="https://www.latindex.org/latindex/inicio" target="_blank" rel="noopener noreferrer">Latindex (Catalog 2.0)</a>,
                <a href="https://www.scielo.br/" target="_blank" rel="noopener noreferrer">SciELO Brazil</a>,
                <a href="https://www.redalyc.org/" target="_blank" rel="noopener noreferrer">Redalyc</a>,
                <a href="https://doaj.org/" target="_blank" rel="noopener noreferrer">DOAJ</a>.
              </li>
            </ul>
          </div>

          <h3>
            <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#preprint" aria-expanded="false" aria-controls="preprint">
              <?= $this->transEsc('Preprint servers'); ?>
            </button>
          </h3>
          <div class="collapse" id="preprint">
            <ul>
              <li>
                <?= $this->transEsc('dlm p1'); ?>
                <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('dlm  OAI link'); ?>
                </a>
                <?= $this->transEsc('dlm p2'); ?>
              </li>
              <li>
                <?= $this->transEsc('lr p0'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p4'); ?>
                <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                  <?= $this->transEsc('Dublin Core'); ?>
                </a>
                <?= $this->transEsc('dlm p5'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p6'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p7'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p8'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p9'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p10'); ?>
              </li>
              <li>
                <?= $this->transEsc('dlm p11'); ?>
                <a href="<?= $this->basePath('/MODELO-DE-OFICIO.docx') ?>"
                  target="_blank"
                  rel="noopener noreferrer">
                  <?= $this->transEsc('dlm modelo'); ?> (docx)
                </a>
              </li>
              <li>
                <?= $this->transEsc('dlm p12'); ?>
              </li>
              <li>
                <?= $this->transEsc('ps p1'); ?>
              </li>
              <li>
                <?= $this->transEsc('ps p2'); ?>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-12">
      <div class="card">
        <h2>
          <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#dark" aria-expanded="false" aria-controls="dark">
            <?= $this->transEsc('dARK — Decentralized Archival Resource Key'); ?>
          </button>
        </h2>
        <div class="collapse" id="dark">
          <p>O dARK é uma iniciativa aberta e gratuita, coordenada pelo Ibict e LA Referencia em colaboração com parceiros regionais, que estende o identificador ARK (Archival Resource Key) para um modelo descentralizado de atribuição e resolução de PIDs, baseado em rede blockchain permissionada. Integrado ao ecossistema do Oasisbr, o dARK busca ampliar a cobertura de identificadores persistentes no Brasil e no Sul Global, reduzir custos operacionais, reforçar a governança compartilhada e assegurar persistência, proveniência e interoperabilidade dos registros ao longo do tempo.
            <br> Saiba mais em:<a href="https://www.dark-pid.net/pt/home" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">
              https://www.dark-pid.net/pt/home.
            </a>
          </p>
          <p>Principais características</p>
          <ul>
            <li>
              Baixo custo e escalabilidade para atribuição de ARKs em larga escala, com ênfase em instituições de países do Sul Global.
            </li>
            <li>
              Interoperabilidade com resolutores ARK globais e convivência com outros PIDs (por exemplo, DOI), preservando vínculos e referências.
            </li>
            <li>
              Governança distribuída em consórcio institucional, aumentando resiliência e tolerância a falhas.
            </li>
            <li>
              Transparência e proveniência dos metadados, favorecendo auditoria, reprodutibilidade e preservação de longo prazo.
            </li>
          </ul>
          <p>Finalidade no Oasisbr</p>
          <ul>
            <li> Ao integrar-se ao Oasisbr, o dARK potencializa a visibilidade, a confiabilidade e a longevidade dos objetos digitais agregados, alinhando-se às práticas de Ciência Aberta e fortalecendo a infraestrutura nacional de comunicação científica.
            </li>
            <li>
              Se sua fonte já faz parte do Oasisbr, baixe o <a href="https://docs.google.com/document/d/1ktJ5g3ZUboYdTFC9uZYeIyc-STtTKtoNrKq_-Porc9s/edit?usp=sharing" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">
                ofício </a> de adesão do dARK e encaminhe para o e-mail <a href="mailto:oasisbr@ibict.br" target="_blank">oasisbr@ibict.br</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-12">
      <div class="card">
        <h2 id="certificacao-lattes-oasisbr">
          <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#certificacao-lattes" aria-expanded="false" aria-controls="certificacao-lattes">
            <?= $this->transEsc('Certificação Lattes-Oasisbr'); ?>
          </button>
        </h2>
        <div class="collapse" id="certificacao-lattes">

          <h3> <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#certificacao" aria-expanded="false" aria-controls="certificacao">
              <?= $this->transEsc('O que é a certificação?'); ?></button>
          </h3>
          <div class="collapse" id="certificacao">
            <p>Os usuários do Currículo Lattes, do CNPq, contam com a possibilidade de terem suas teses e dissertações certificadas pelo Oasisbr - Portal Brasileiro de Publicações e Dados Científicos em Acesso Aberto. Mais de um milhão de teses e dissertações brasileiras do Currículo Lattes já contam automaticamente com o selo Oasisbr.
            </p>
            <p>O selo de certificação é exibido nas informações do currículo do usuário, nas seções de informações acadêmicas/titulação e orientações concluídas. Com o selo, é possível comprovar, de maneira rápida e simples, a autoria/orientação concluída da tese ou dissertação e acessar o documento em acesso aberto no Oasisbr. O certificado poderá ser emitido de forma automática pelo Currículo Lattes ou cadastrado manualmente pelo usuário.</p>
            <p>Com a nova funcionalidade, o CV Lattes poderá verificar se a tese ou dissertação inserida no currículo do pesquisador está disponível em alguma base ou repositório acadêmico. Este será o primeiro passo para outras certificações à caminho.
            </p>
          </div>
          <h3> <button type="button" data-bs-toggle="collapse" class="btn-collapse collapsed" href="#passo-a-passo" aria-expanded="false" aria-controls="passo-a-passo">
              <?= $this->transEsc('Como inserir o selo do Oasisbr no Currículo Lattes?'); ?></button>
          </h3>
          <div class="collapse" id="passo-a-passo">
            <p>A tese ou dissertação cadastrada na plataforma Lattes poderá ser certificada apenas se o documento estiver inserido no portal Oasisbr, então, primeiramente o usuário deverá se certificar entrando no site do portal. Em um primeiro momento a certificação Lattes pelo Oasisbr pode ser realizada para Teses e Dissertações defendidas e orientadas por programas de pós-graduação brasileiros, a certificação de outros documentos acontecerá de forma gradual.
            </p>
            <p><strong>IMPORTANTE!</strong> A importação será realizada apenas se os dados do título e ano de publicação estiverem condizentes, tanto no Oasisbr quanto no seu currículo Lattes.
            </p>
            <p>Se o documento não estiver cadastrado no Portal Oasis, pedimos que notifique a instituição depositante, solicitando o cadastramento do repositório junto ao nosso portal através do e-mail oasisbr@ibict.br.
            </p>
            <p>Ao acessar o seu espaço de edição do Currículo Lattes e inserir os dados de uma tese ou dissertação, o pesquisador ou acadêmico pode importar informações do Oasisbr pelo seu ID Lattes ou número do ORCID e verificar quais são os documentos cadastrados no Oasisbr. Os dados importados já vem com o selo para serem exibidos automaticamente no perfil público. Ao clicar no selo, o usuário poderá acessar o documento no Oasisbr.</p>
            <a href="<?= $this->basePath('/passo-a-passo-para-certificacao-lattes-oasisbr.pdf') ?>"
              target="_blank"
              rel="noopener noreferrer">
              Veja o passo a passo para certificação (PDF)
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>