<?php
// Set page title.
$this->headTitle($this->translate('Record Citations'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
  . '<li>' . $this->recordLinker()->getBreadcrumb($this->driver) . '</li> '
  . '<li class="active">' . $this->transEsc('Record Citations') . '</li>';

// Collect citation data:
$helper = $this->citation($this->driver);
$citations = [];
foreach ($this->driver->getCitationFormats() as $format) {
  $citations[$format . ' Citation'] = $helper->getCitation($format);
}
?>
<?php if (count($citations) == 0) : ?>
  <?= $this->transEsc('No citations are available for this record') ?>
<?php else : ?>
  <?php foreach ($citations as $caption => $citation) : ?>
    <strong><?= $this->transEsc($caption) ?></strong>
    <p class="text-left">
      <?= $citation ?>
    </p>
  <?php endforeach; ?>
  <div class="text-muted text-center">
    <?= $this->transEsc("ABNT Citation Note") ?>
    <a href="https://zenodo.org/record/6376312" target="_new" rel="noopener noreferrer">Zotero</a>
    <?= $this->transEsc("ABNT Citation Note2") ?>
  </div>
<?php endif; ?>