<?php
  // Set page title.
  $this->headTitle($this->translate('Record Citations'));

  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($this->translate('Record Citations'), active: true);

  // Collect citation data:
  $helper = $this->citation($this->driver);
  $citations = [];
  foreach ($this->driver->getCitationFormats() as $format) {
    $citations[$format] = $helper->getCitation($format);
  }
?>
<?php if (count($citations) == 0) : ?>
  <?= $this->transEsc('No citations are available for this record') ?>
<?php else : ?>
  <?php foreach ($citations as $format => $citation) : ?>
    <?php
      $shortCaption = $this->translate($format . ' Citation');
      $longCaption = $this->translate($format . ' Edition Citation');
      $caption = (strpos($longCaption, 'Citation') > 0 && !str_contains($shortCaption, 'Citation'))
        ? $shortCaption : $longCaption;
      $elementId = 'citation-' . $this->escapeHtmlAttr($format);
    ?>
    <strong><?= $this->escapeHtml($caption) ?></strong>
    <div class="citation copy-to-clipboard-container">
      <span id="<?= $elementId ?>">
        <?= $citation ?>
      </span>
      <?= $this->copyToClipboardButton('#' . $elementId) ?>
    </div>
  <?php endforeach; ?>
  <div class="text-muted bg-muted p-2">
    <?= $this->transEsc("ABNT Citation Note") ?>
    <a href="https://zenodo.org/record/6376312" target="_new" rel="noopener noreferrer">Zotero</a>
    <?= $this->transEsc("ABNT Citation Note2") ?>
  </div>
<?php endif; ?>
