<?php
$start = $this->localizedNumber($this->results->getStartRecord());
$end = $this->localizedNumber($this->results->getEndRecord());
$total = $this->localizedNumber($recordTotal);
$queryTime = $this->results->getQuerySpeed();
$lookfor = $this->escapeHtml($lookfor ?? '');
$transParams = [
  '%%start%%' => $start,
  '%%end%%' => $end,
  '%%total%%' => $total,
  '%%lookfor%%' => $lookfor,
];
?>
<span class="js-search-stats" data-key="showing_results_of_for_html">
  <?= $this->translate('showing_results_of_for_html', $transParams) ?><?php if ($queryTime !== null) : ?>, <?= $this->transEsc('query time') ?>: <?= $this->localizedNumber($queryTime, 2) . $this->transEsc('seconds_abbrev') ?><?php endif; ?>
</span>