<?php
$userLang = str_replace('_', '-', $this->layout()->userLang);

$htmlLang = match (strtolower($userLang)) {
  'pt-br', 'pt' => 'pt-BR',
  'en', 'en-us' => 'en-US',
  default => $userLang,
};
?>

<?= $this->doctype('HTML5') ?>
<html lang="<?= $this->escapeHtmlAttr($htmlLang) ?>" <?= $this->layout()->rtl ? ' dir="rtl"' : '' ?>>

<head>
  <?php $this->setupThemeResources(); ?>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <?= $this->headMeta() ?>
  <?= $this->headTitle() ?>
  <?php
  // Set up OpenSearch link:
  $this->headLink(
    [
      'href' => $this->url('search-opensearch') . '?method=describe',
      'type' => 'application/opensearchdescription+xml',
      'title' => $this->transEsc('Library Catalog Search'),
      'rel' => 'search'
    ]
  );
  ?>
  <!-- RTL styling -->
  <?php if ($this->layout()->rtl) {
    $this->assetManager()->appendStyleLink('vendor/bootstrap-rtl.min.css');
  } ?>
  <?php
  // Render icons early; VuFind's JS configuration needs them before initialization.
  $icons = !isset($this->renderingError) ? $this->render('js-icons.phtml') : '{}';
  ?>

  <?php
  // Collect small scripts together and append as one block:
  $appendScripts = [];
  $themeConfig = $this->themeConfig();
  if (!empty($themeConfig['stickyElements'])) {
    $this->assetManager()->appendScriptLink('sticky_elements.js');
  }

  if (!isset($this->renderingError)) {
    // Add translation strings
    $this->jsTranslations()->addStrings(
      [
        'add_tag_success' => 'add_tag_success',
        'bulk_email_success' => 'bulk_email_success',
        'bulk_noitems_advice' => 'bulk_noitems_advice',
        'bulk_save_success' => 'bulk_save_success',
        'close' => 'close',
        'collection_empty' => 'collection_empty',
        'eol_ellipsis' => 'eol_ellipsis',
        'error_occurred' => 'An error has occurred',
        'go_to_list' => 'go_to_list',
        'hold_available' => 'hold_available',
        'libphonenumber_invalid' => 'libphonenumber_invalid',
        'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
        'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
        'libphonenumber_notanumber' => 'libphonenumber_notanumber',
        'libphonenumber_toolong' => 'libphonenumber_toolong',
        'libphonenumber_tooshort' => 'libphonenumber_tooshort',
        'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
        'loading' => 'Loading',
        'more' => 'more',
        'number_thousands_separator' => [
          'number_thousands_separator',
          null,
          ','
        ],
        'sms_success' => 'sms_success'
      ]
    );
    // Add libphonenumber.js strings
    $this->jsTranslations()->addStrings(
      [
        "Phone number invalid" => 'libphonenumber_invalid',
        "Invalid country calling code" => 'libphonenumber_invalidcountry',
        "Invalid region code" => 'libphonenumber_invalidregion',
        "The string supplied did not seem to be a phone number" => 'libphonenumber_notanumber',
        "The string supplied is too long to be a phone number" => 'libphonenumber_toolong',
        "The string supplied is too short to be a phone number" => 'libphonenumber_tooshort',
        "Phone number too short after IDD" => 'libphonenumber_tooshortidd'
      ]
    );
    // Deal with cart stuff:
    $cart = $this->cart();
    if ($cart->isActive()) {
      $this->assetManager()->appendScriptLink('vendor/js.cookie.js');
      $this->assetManager()->appendScriptLink('cart.js');
      $this->jsTranslations()->addStrings(
        [
          'addBookBag' => 'Add to Book Bag',
          'bookbagFull' => 'bookbag_full_msg',
          'bookbagMax' => $cart->getMaxSize(),
          'bookbagStatusFull' => 'bookbag_full',
          'confirmDelete' => 'confirm_delete',
          'confirmEmpty' => 'bookbag_confirm_empty',
          'itemsAddBag' => 'items_added_to_bookbag',
          'itemsInBag' => 'items_already_in_bookbag',
          'removeBookBag' => 'Remove from Book Bag',
          'viewBookBag' => 'View Book Bag'
        ]
      );
    }
    $this->assetManager()->prependScriptString(
      'var userIsLoggedIn = ' . ($this->auth()->getUserObject() ? 'true' : 'false') . ';'
    );
  }

  // Session keep-alive
  if ($this->keepAlive()) {
    $appendScripts[] = 'var keepAliveInterval = ' . $this->keepAlive() . ';';
    $this->assetManager()->appendScriptLink('keep_alive.js');
  }

  // If account ajax is active, load script and add language strings
  $account = $this->auth()->getManager();
  if ($account->ajaxEnabled()) {
    $this->assetManager()->appendScriptLink('account_ajax.js');
    $this->jsTranslations()->addStrings(
      [
        'account_checkouts_due' => 'account_checkouts_due',
        'account_checkouts_overdue' => 'account_checkouts_overdue',
        'account_has_alerts' => 'account_has_alerts',
        'account_normal_checkouts' => 'account_normal_checkouts',
        'account_requests_available' => 'account_requests_available',
        'account_requests_in_transit' => 'account_requests_in_transit',
      ]
    );
  }

  $root = rtrim($this->url('home'), '/');
  $jsConfig = !isset($this->renderingError) ? $this->render('js-configs.phtml') : '{}';
  $translations = !isset($this->renderingError) ? $this->render('js-translations.phtml') : '{}';
  $dsb = DEFAULT_SEARCH_BACKEND;
  $cspNonce = $this->csp()->getNonce();
  $searchId = json_encode($this->layout()->searchId);
  $theme = json_encode($themeConfig['themeName']);
  $appendScripts[] = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.config.add({$jsConfig});
VuFind.addTranslations({$translations});
VuFind.addIcons({$icons});
VuFind.setCspNonce('{$cspNonce}');
VuFind.setCurrentSearchId($searchId);
VuFind.setTheme($theme);
JS;
  if ($domain = $this->cookieManager()->getDomain()) {
    $appendScripts[] = 'VuFind.cookie.setDomain(' . json_encode($domain) . ');';
  }
  if ($cookiePath = $this->cookieManager()->getPath()) {
    $appendScripts[] = 'VuFind.cookie.setCookiePath(' . json_encode($cookiePath) . ');';
  }
  if ($cookieSameSite = $this->cookieManager()->getSameSite()) {
    $appendScripts[] = 'VuFind.cookie.setCookieSameSite(' . json_encode($cookieSameSite) . ');';
  }
  $this->assetManager()->appendScriptString(implode("\n", $appendScripts));

  if ($this->config()->ajaxCoversEnabled()) {
    $this->assetManager()->appendScriptLink('covers.js');
  }
  ?>
  <?= $this->assetManager()->outputHeaderAssets() ?>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-V8YFC4NWSB"></script>

  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-V8YFC4NWSB');
  </script>
  <meta name="google-site-verification" content="O4MlrfmxB744id4GdcKmv79sPQNLIjWzEB_VV9o1byw" />
</head>

<body class="oasis-site template-dir-<?= $this->templateDir ?> template-name-<?= $this->templateName ?> <?= $this->layoutClass('offcanvas-row') ?><?php if ($this->layout()->rtl) : ?> rtl<?php endif; ?>">
  <?php // Set up the search box -- there are three possible cases:
  // 1. No search box was set; we should default to the normal box
  // 2. It was set to false; we should display nothing
  // 3. It is set to a custom string; we should display the provided version
  // Set up default search box if no data was provided from the template;
  // this covers case 1.  Cases 2 and 3 are then covered by logic below.
  if (!isset($this->layout()->searchbox)) {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
  }
  ?>
  <header class="d-print-none">
    <?php if (isset($this->layout()->srmessage)) : // message for benefit of screen-reader users 
    ?>
      <span class="visually-hidden" role="heading" aria-level="1"><?= $this->layout()->srmessage ?></span>
    <?php endif; ?>
    <a class="visually-hidden-focusable skip-link" href="#content"><?= $this->transEsc('Skip to content') ?></a>
    <a class="visually-hidden-focusable skip-link" href="#header-collapse"><?= $this->transEsc('Skip to navigation menu') ?></a>
    <?= $this->render('header.phtml') ?>
  </header>
  <?php if ($this->layout()->searchbox !== false) : ?>
    <div class="searchHomeContent">
      <div class="search container navbar">
        <nav class="nav searchbox d-print-none">
          <?= $this->layout()->searchbox ?>
        </nav>
      </div>
    </div>
  <?php endif; ?>
  <?= $this->breadcrumbs()->render() ?>
  </div>
  </nav>
  <main class="main">
    <div id="content" class="<?php if (!$this->layout()->nocontainerclass) : ?>container<?php endif; ?>">
      <?= $this->layout()->content ?>
    </div>
  </main>
  <?= $this->render('footer.phtml') ?>
  <!-- MODAL IN CASE WE NEED ONE -->
  <div id="modal" class="modal fade d-print-none" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title"></h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= $this->transEscAttr('Close') ?>"></button>
        </div>
        <div class="modal-body" aria-live="polite"><?= $this->transEsc('Loading') ?>...</div>
      </div>
    </div>
  </div>
  <!-- <div class="offcanvas-overlay" data-bs-toggle="offcanvas" role="button" tabindex="0" aria-label="Fechar menu"></div> -->
  <button type="button" class="offcanvas-overlay" data-bs-toggle="offcanvas" aria-label="<?= $this->transEscAttr('Fechar menu') ?>"></button>
  <?= $this->googleanalytics() ?>
  <?= $this->piwik() ?>
  <?php foreach ($this->captcha()->js() as $jsInclude) : ?>
    <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, $jsInclude, 'SET') ?>
  <?php endforeach; ?>

  <!-- <script async src="https://cdn.userway.org/widget.js" data-account="gxYK4Xrqhn"></script> -->
  <?= $this->assetManager()->outputFooterAssets() ?>
</body>

</html>
