<?php $this->headTitle('Dicas Avançadas de Pesquisa'); ?>
<?php $this->layout()->searchbox = false; ?>
<?php $this->layout()->breadcrumbs .= '<li class="active">' . '' . '</li>'; ?>

<div class="fulltext">
  <h1 class="text-primary">Dicas Avançadas de Pesquisa</h1>

  <dl class="Content">
    <dt class="text-secondary">Campos de Busca</dt>
    <dd>
      <p>A página de Busca Avançada apresenta a vários campos de busca.
        Em cada campo pode-se digitar termos, a qual deseja buscar itens, relacionando-os a determinado metadado,
        podendo fazer uso de <a href="<?= $this->url('help-home') ?>?topic=search">operadores de busca</a>
      </p>
      <p>Pode-se selecionar o tipo de metadado (título, autor, etc.) para cada campo de busca,
        tornando a busca mais precisa.
      </p>
      <p>Da mesma forma, pode-se combimar mais que um campo de busca.</p>

      <ul>
        <li>Todos os termos - Retorna somente os itens que possuam todos os termos inseridos nos campos.</li>
        <li>Algum termo - Retorna os itens que possuam pelo menos um dos termos inseridos nos campos.</li>
        <li>Sem os termos - Retorna todos os itens, exceto os que possuem os termos inseridos no campo.</li>
      </ul>
      <p>O Botão "Adicionar campo de busca" pode ser usado para adicionar campos de busca extras ao formulário.
        Pode-se adicionar quantos campos forem necessários.</p>
    </dd>

    <dt class="text-secondary">Grupos de Busca</dt>
    <dd>
      <p>Para certas buscas complexas, um conjunto simples de campos de busca podem não ser o bastante.
        Por exemplo, suponhe que deseje encontrar os itens sobre a história de São Paulo ou Rio de Janeiro.
        Caso use a opção "Todos os termos" recuperará itens que contenham história de São Paulo E Rio de Janeiro.
        Caso use a opção "Algum termo" recuperará itens que contêm nada de São Paulo ou Rio de Janeiro.
      </p>
      <p>Grupos de busca prove um meio de construir buscas agrupando campos de busca.
        Cada vez que pressionar o botão "Adicionar outros campos de busca" um novo grupo de campos será adicionado.
        Uma vez que tenha múltiplos grupos de busca, pode-se remover grupos indesejados utilizando o botão
        "Retirar o grupo de busca". Pode-se especificar se deseja buscar em todos os grupos ou em alguns dos grupos.
      </p>
      <p>No exemplo anterior, pode-se resolver com a seguinte estratégia de busca, utilizando os grupos de busca:</p>
      <ul>
        <li>No primeiro grupo, insira "São Paulo" e "Rio de Janeiro" selecionando "Algum termo".</li>
        <li>Adicione um segundo grupo e insira "história".</li>
        <li>Selecione "Todos os Grupos" no cabeçalho e faça a busca.</li>
      </ul>
    </dd>
  </dl>
</div>